repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        files: ^backend/
        language_version: python3

  - repo: local
    hooks:
      - id: frontend-prettier
        name: Frontend Prettier
        entry: bash -c 'cd frontend && npm run format'
        files: ^frontend/
        language: system
        pass_filenames: false
