app = "artisan-chatbot-api"
primary_region = "sin"  # Singapore - you can change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "sqlite_data"
  destination = "/data"
